### ISSUE TITLE
New developments: summed likelihood, test models macro, EBL absorption, decorrelation energy

### ISSUE THREAD

**Issue by mireianievas** [gammapy/enrico#100]
Dear all,

As you may know, I've been working lately to implement:

- Summed Likelihood by default. The single analysis would become thus a summedlikelihood with 1 component only.
- This has some implications, since enrico_testmodel stopped working (with summedlikelihood you have to run some of the actions individually for each component in SummedLikelihood.components.
- The diagnostic plots stopped working (they are not implemented in the Fermi ScienceTools for SummedLikelihood) but I managed to impelement them directly at enrico.
- EBL models. There was some code written (partly related to the configuration file), but nothing really working in enrico. I wrote down some code to be able to actually use those models following 
https://confluence.slac.stanford.edu/display/ST/Likelihood+Usage+Notes#LikelihoodUsageNotes-EBLAttenuationmodels(20June2009). 
- I also included more models that are available in the Science Tools. Now they run up to model=20 (inc. Dominguez '11 = model 10). http://www-glast.stanford.edu/cgi-bin/viewcvs/celestialSources/eblAtten/eblAtten/EblAtten.h?view=markup
- One small note: powerlaw is not among the implemented models, i.e., there is no EblAtten::PowerLaw. However, its behavior can be implemented easily with a LogParabola with frozen b=0. I went for that case.

An example of all this: LogParabola + EBL from Dominguez '11 on a PG1553 sample

![image](https://cloud.githubusercontent.com/assets/2607760/20604338/2c333fd8-b266-11e6-9cf5-eb09528c233c.png)

- the spectral parameters in the result file are now refereed to the decorrelation energy (Scale for PowerLaw, Eb for LogParabola for instance). I guess that makes more sense than reporting them for Emin.
- I added another FARM type 'LOCAL' with a niceness value of 19 in the jobs and the possibility to specify the QUEUE (through env variable).

Part of these changes were already included in the main repository, but I've polished / improved them and I'm currently testing them. You can find the changes https://github.com/mireianievas/enrico
As soon as I'm happy enough with the current behavior I will make a pull request.

**Comment by davidsanchez** [comment]
thanks a lot for all the work

**Comment by davidsanchez** [comment]
yes please, make the pul lrequest and I would be happy to merge the code

**Comment by mireianievas** [comment]
Ok, there's something here to comment. The list of models in the official release of the ScienceTools is not the one I posted, but in v10r0p5 it is 

Kneiske, Primack05, Kneiske_HighUV, Stecker05,
Franceschini, Finke, Gilmore, Stecker05_FE,
SalamonStecker, Generic, Gilmore12_fixed, Gilmore12_fiducial

So model=10 is not Dominguez 11, but Gilmore12_fixed. 

Fortunately, they are relatively close in the LAT energies and unless a strong and hard flaring source is  being analyzed, I doubt it would make a difference. Franceschini is quite close to those too, so one can always use that, which is still in 2017 quite a gold standard.

**Comment by davidsanchez** [comment]
thanks for the notice
