### ISSUE TITLE
enrico_lc float to int rounding error in utils.py

### ISSUE THREAD

**Issue by tbrandonstevenson** [gammapy/enrico#101]
There is an issue with the str(int(float)) lines in the _dump_filename(config) function for utils.py, where floats are being truncated sometime causinga roundoff error of 1, and thus not allowing enrico_plot_lc to load the correct lc filenames.

**Comment by davidsanchez** [comment]
thanks for reporting the bug

**Comment by mireianievas** [comment]
I guess a simple +0.5 will do it. I've implemented it in my fork, but anyway, I've other changes (one that affects an issue I unintentionally created with the UpperLimit generation) that I want to check (give me some days :) ) before making a pull request.

**Comment by davidsanchez** [comment]
thanks. please make the pull request when you can
best
david
