### ISSUE TITLE
enrico_plot_lc  issue

### ISSUE THREAD

**Issue by castroavila** [gammapy/enrico#103]
Hi, 

I have pulled the latest enrico version and when I execute enrico_plot_lc, I get this error:

[LightCurve]: Reading files produced by enrico
TROOT::Append:0: RuntimeWarning: Replacing existing TH1: ghnpred (Potential memory leak).
Traceback (most recent call last):
  File "/home/castro/PROGRAMS/enrico/bin/enrico_plot_lc", line 30, in <module>
    lc.PlotLC()
  File "/home/castro/PROGRAMS/enrico/enrico/lightcurve.py", line 208, in PlotLC
    self._PlotLC()
  File "/home/castro/PROGRAMS/enrico/enrico/lightcurve.py", line 316, in _PlotLC
    TgrNpred_detected.SetLineColor(2)
AttributeError: 'tuple' object has no attribute 'SetLineColor'

I'm not sure if this error is associated with ROOT or ?

Thanks in advance,
Manuel

**Comment by davidsanchez** [comment]
Hi
could you attache the config file and the output
thanks
david

**Comment by castroavila** [comment]
Hi David,

Thanks for the reply. I attach the files.

[output.txt](https://github.com/gammapy/enrico/files/913716/output.txt)
[myanalysis_config.txt](https://github.com/gammapy/enrico/files/913720/myanalysis_config.txt)

Cheers,
Manuel

**Comment by davidsanchez** [comment]
I guess fix the problem
could you check?
thanks

**Comment by castroavila** [comment]
Hi David, 
Yes, that fix the issue. But now, another issue is shown:

[output.txt](https://github.com/gammapy/enrico/files/919610/output.txt)

I use the same .conf file.

**Comment by davidsanchez** [comment]
did you move  or rename the .results file?

**Comment by castroavila** [comment]
No, but  the issue is about a file that should be at the same directory as both the *SC.fits and *PH.fits files. To my understanding all files generated by enrico_lc are placed under "LightCurve_417bins" directory. Another thing is that file is named "J0131.2+6120_PowerLaw_241920001_494380804_100_500000_weekly.results", where 241920001 and 494380804  are tmin and tmax in the .config file and not a range for a specific bin.

**Comment by davidsanchez** [comment]
did you run enrico_sed first? the index is needed for the variability index to be computed.

**Comment by castroavila** [comment]
No, I didn't. Is it necessary before running enrico_lc?  Do I need to set NumEnergyBins>0  or ?

**Comment by davidsanchez** [comment]
enrico_sed is need to run the variability index caclulation. beyond that tecnically no. 
I'll had a warning and a try in the code

**Comment by davidsanchez** [comment]
This will be in the next version of the code
thanks
