### ISSUE TITLE
enrico_setupcheck: manually set variables

### ISSUE THREAD

**Issue by pmunar** [gammapy/enrico#107]
Hi everyone!

I am having some problems with the installation of Enrico on my macbook pro (but I do not think it is related to the mac itself, but related to the python installation).
I have an anaconda python 2.7 installation, and I installed the Fermi Science tools version ScienceTools-v10r0p5-fssc-patch-20150518-x86_64-apple-darwin14.4.0-without-root

When I load the HEASOFT, Fermi Science tools and then Enrico packages, and I run enrico_setupcheck, there are some packages that are not seen:

pyfits.............. MISSING
UnbinnedAnalysis.... MISSING
BinnedAnalysis...... MISSING

My guess is that without those packages, the analysis cannot be done properly. Since I have installed those packages, and I know where they are, is there a way to manually tell enrico where can they be found? 

I have looked into the enrico code in order to check where were these packages checked, but I did not find it.

Thanks for your help!

Cheers,
    
    Pere

**Comment by davidsanchez** [comment]
Hi
those packages should come with the Fermi ST.
cheers
david
