### ISSUE TITLE
 source $ENRICO_DIR/enrico-init.sh

### ISSUE THREAD

**Issue by steventheuniverse** [gammapy/enrico#115]
Stevens-MacBook-Pro:enrico StevenZakirov$ source $ENRICO_DIR/enrico-init.sh
Adding Enrico to PATH and PYTHONPATH
Setting environment variables for data file locations
mkdir: /Users/davidsanchez/Soft/enrico/Data: Permission denied
mkdir: /Users/davidsanchez/Soft/enrico/Data/diffuse: Permission denied
mkdir: /Users/davidsanchez/Soft/enrico/Data/download: Permission denied
mkdir: /Users/davidsanchez/Soft/enrico/Data/preprocessed: Permission denied
mkdir: /Users/davidsanchez/Soft/enrico/Data/catalog: Permission denied
Run enrico_setupcheck to check if you are set up correctly.
Check your PATH and PYTHONPATH if enrico_setup is not found or gives an error.

- Im not sure what happened but i cant get past this step

**Comment by davidsanchez** [comment]
Hi,
You have to change the scripts for your own installation . This should be in the documentation.
Cheers
