### ISSUE TITLE
enrico_sed myanalysis.conf: Plot SED fails with Fatal Python Error

### ISSUE THREAD

**Issue by steventheuniverse** [gammapy/enrico#116]
I am running the basic tutorial analysis 
Here is by bash_profile

# added by Anaconda3 4.2.0 installer
export PATH="//anaconda/bin:$PATH"

export FERMI_DIR=/Users/StevenZakirov/Desktop/SRMP/ScienceTools-v10r0p5-fssc-20160831/x86_64-apple-darwin15.6.0
source $FERMI_DIR/fermi-init.sh

export ENRICO_DIR=/Users/StevenZakirov/Desktop/SRMP/enrico-master
export PATH="/Users/StevenZakirov/anaconda/bin:$PATH"
source $ENRICO_DIR/enrico-init.sh

alias rm="rm -i"

# Setting PATH for Python 3.5
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH

. /Applications/root_v6.10.08/bin/thisroot.sh

Here is my error while running enrico_sed myanalysis.conf

# ************************************************************
# ***  12    PlotSED --- Generate SED plot
# ************************************************************
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

**Comment by davidsanchez** [comment]
Hi
I have never use python3 and enrico is design for python2.  I am not sure that the ST are python3 ready
cheers
david

**Comment by steventheuniverse** [comment]
Hello, thank you for responding. Can you recommend what I should do about the error? Should I just uninstall python 3 and install python 2?

**Comment by davidsanchez** [comment]
yes

**Comment by steventheuniverse** [comment]
when I run python --version, it says I have 2.7.8 and homebrew also says this. Do I just delete this path in my .bash_profile?  I have 3.5 installed on my computer and if I change it what path do I replace it with?

Setting PATH for Python 3.5
The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH

**Comment by davidsanchez** [comment]
I have to admit that I can help you on this 
sorry

**Comment by mireianievas** [comment]
Just a comment, for the record :)

You should, just to make sure there are no clashes, use the same python interpreter distributed with the Fermi ScienceTools
