### ISSUE TITLE
Enrico_download not to be able to download Fermi weekly data.

### ISSUE THREAD

**Issue by 9635065235** [gammapy/enrico#135]
enrico_download --download_data                                                        
('EXEC: ', 'wget -m -P weekly -nH --cut-dirs=4 -np ftp://legacy.gsfc.nasa.gov/fermi/data/lat/weekly/photon')
--2019-04-09 17:31:08--  ftp://legacy.gsfc.nasa.gov/fermi/data/lat/weekly/photon
           => ‘weekly/.listing’
Resolving legacy.gsfc.nasa.gov (legacy.gsfc.nasa.gov)... 129.164.179.23, 2001:4d0:2310:150::23
Connecting to legacy.gsfc.nasa.gov (legacy.gsfc.nasa.gov)|129.164.179.23|:21... connected.
Logging in as anonymous ... 
Login incorrect.

**Comment by davidsanchez** [comment]
Hi
I can't reproduce this problem with the lastest version of the code
cheers
david
