### ISSUE TITLE
error while performing gtsrcmaps

### ISSUE THREAD

**Issue by basuparth** [gammapy/enrico#144]
I was running a standard analysis after the recent fixes were added when I ran into the following error.

time -p gtsrcmaps scfile=/home/parth/SINP/1ES1218+304veritas/enrico/L190412105317D2B2D19892_SC00.fits sctable="SC_DATA" expcube=/home/parth/SINP/1ES1218+304veritas/enrico/1ES1218+304_LAT_Analysis_ltCube.fits cmap=/home/parth/SINP/1ES1218+304veritas/enrico/1ES1218+304_LAT_Analysis_CCUBE.fits srcmdl=/home/parth/SINP/1ES1218+304veritas/enrico/1ES1218+304_PowerLaw2_model.xml bexpmap=/home/parth/SINP/1ES1218+304veritas/enrico/1ES1218+304_LAT_Analysis_BinnedMap.fits wmap=none outfile=/home/parth/SINP/1ES1218+304veritas/enrico/1ES1218+304_LAT_Analysis_PowerLaw2_srcMap.fits irfs="P8R3_SOURCE_V2" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.1 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=2 clobber=yes debug=no gui=no mode="ql"

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Using evtype=3 (i.e., FRONT/BACK irfs)
facilities::WrongType. Cannot convert '<!DOCTYPE'to type double
Caught N10facilities9WrongTypeE at the top level: facilities::WrongType. Cannot convert '<!DOCTYPE'to type double
Traceback (most recent call last):
  File "/home/parth/enrico/bin/enrico_sed", line 53, in <module>
    sed(config,infile)
  File "/home/parth/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/parth/enrico/enrico/RunGTlike.py", line 147, in run
    FitRunner,Fit = GenAnalysisObjects(config)
  File "/home/parth/enrico/enrico/RunGTlike.py", line 123, in GenAnalysisObjects
    tag=typeirfs[evt], verbose = verbose)
  File "/home/parth/enrico/enrico/RunGTlike.py", line 25, in Analysis
    FitRunner.GenerateFits() #Generates fits files for the rest of the products
  File "/home/parth/enrico/enrico/fitmaker.py", line 82, in GenerateFits
    self.obs.SrcMap()
  File "/home/parth/enrico/enrico/gtfunction.py", line 409, in SrcMap
    srcMaps.run()
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermitools/GtApp.py", line 76, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtsrcmaps execution failed
[myanalysis.txt](https://github.com/gammapy/enrico/files/3271391/myanalysis.txt)

**Comment by davidsanchez** [comment]
Hi
I try to have a look into it

**Comment by mireianievas** [comment]
Probably the content of the iso file is wrong and contains a 403/404-like html response? I am having a look at this and a few other issues.
