### ISSUE TITLE
installation problem in Mac air 

### ISSUE THREAD

**Issue by ajaykhoj** [gammapy/enrico#172]
Hi,

I was trying to install Enrico in Mac air, but getting error while sourcing" source $ENRICO_DIR/enrico-init.sh". And error that I am getting, 
/Users/ajaysharma/enrico/enrico-init.sh:18: = not found

could you please suggest any alternative way to do this ?
Thanks in advance

**Comment by davidsanchez** [comment]
hi
this is because your shell is zsh . You should translate the .sh into a zsh file
cheers
david

**Comment by ajaykhoj** [comment]
This problem has been resolved.
