### ISSUE TITLE
Update 2FGL -> 3FGL in Enrico (or support both)

### ISSUE THREAD

**Issue by vaidehiratna** [gammapy/enrico#65]
Hi,
Any idea regarding the time of release of 3 FGL catalog? Actually now a days referees have started asking to include unmodeled sources by generating TS maps. For one or two sources, this can be done, however, if someone wants to use a large sample (say 100 blazars), then generating TS map of 100 sources will be too time and memory consuming. So is there any alternate of searching unmodeled sources from TS maps or we need to wait till 3 FGL comes up?
Thanks.

**Comment by cdeil** [comment]
@vaidehiratna - `enrico` is one of the "user contributions" (http://fermi.gsfc.nasa.gov/ssc/data/analysis/user/), it's not maintained by the Fermi LAT collaboration.

I'd suggest you ask your questions to the Fermi LAT collaboration:
http://fermi.gsfc.nasa.gov/ssc/help/

As far as I know there's no good automatic tool (in Enrico or anywhere) to model the sources that are not in 2FGL.

**Comment by cdeil** [comment]
@vaidehiratna - Yesterday the release of the 3FGL catalog was announced on the fermi-news mailing list ... it's now available here: http://fermi.gsfc.nasa.gov/ssc/data/access/lat/4yr_catalog/

I'm re-opening this issue, because we should probably update and re-test enrico to use 3FGL:
https://github.com/gammapy/enrico/search?utf8=%E2%9C%93&q=2fgl

**Comment by davidsanchez** [comment]
The 3FGL fits files is structured in the same way as the 2FGL. then I only change the downloading process.

the changes have been committed

**Comment by cdeil** [comment]
@davidsanchez Can you also change the docs?

* 2FGL is currently mentioned in many places: https://github.com/gammapy/enrico/search?utf8=%E2%9C%93&q=2FGL&type=Code
* 3FGL is currently mentioned nowhere: https://github.com/gammapy/enrico/search?utf8=%E2%9C%93&q=3FGL

Should both 2FGL and 3FGL be downloaded and mentioned, or 3FGL only?

**Comment by davidsanchez** [comment]
I have changed the doc
D
