### ISSUE TITLE
Software Version in outputs

### ISSUE THREAD

**Issue by ctrichard** [gammapy/enrico#66]
Dear all,

Thanks for this very useful package.

I noticed that no information concerning Sciencetools version, Enrico version (if there are any), Data processing version, etc... are shown in outputs.

I think such information may be useful to check and compare old analyses.

Cheers,
Cyril.

**Comment by cdeil** [comment]
Agreed this would be very useful to have.
Should this info go into the log or to a separate `analysis-versions.json` file?
What's the "data processing version"?

**Comment by ctrichard** [comment]
In my point of view, this should be in the log file (to have all information there) or at least in the .conf file. But in the .results as well could be convenient.

I was refering to the P7, P7Rep, P8 .... version name of the fermi data.

**Comment by davidsanchez** [comment]
Hi

I did not manage to get the ST version. The data version is a number stored in the header. for P7Rep this is 203. I print also the Fermi install path

still testing

D

**Comment by cdeil** [comment]
This should work for most users:
```python
import os

def get_sciencetools_info():
    """Determine Fermi ScienceTools path and version"""
    import pyLikelihood
    path = os.path.realpath(pyLikelihood.__file__)
    version = 'unknown'
    for token in path.split(os.path.sep):
        if token.startswith('ScienceTools'):
            version = token
    info = dict(path=path, version=version)
    return info

```
gives me
```python
>>> get_sciencetools_info()
{'version': 'ScienceTools-v9r33p0-fssc-20140520-x86_64-apple-darwin12.5.0',
 'path': '/Users/deil/software/fermi/ScienceTools-v9r33p0-fssc-20140520-x86_64-apple-darwin12.5.0/x86_64-apple-darwin12.5.0/lib/python/pyLikelihood.pyc'}
```

But it's a hack ... really there should be an easy way to get the version number from the command line and Python.
kialio - Maybe you have a suggestion?

**Comment by davidsanchez** [comment]
This gives the path of the ST as I am doing but the path can be changed. I take this

**Comment by cdeil** [comment]
Yes, this is a hack.
@davidsanchez - Maybe we should ask via the Fermi Helpdesk if this is already possibly somehow? And if not ask if they could put this in the next version of the ScienceTools?

**Comment by davidsanchez** [comment]
maybe yes

**Comment by cdeil** [comment]
@davidsanchez - Will you contact them or should I do it now?

**Comment by davidsanchez** [comment]
Could you do it please?

**Comment by cdeil** [comment]
Done: `[Fermi #2907] How to check Fermi ScienceTools version programatically?`
I'll report back here when I get a reply...

**Comment by cdeil** [comment]
The reply from the Fermi helpdesk was:
- It's currently not easily possible ... they'll discuss if a `gtversion` tool will be added in the future, in analogy how the `FTOOLs` have an `ftversion` tool:
```
$ ftversion 
23Jun2014_V3.4
```
- One option they mentioned is to run `gtbin` and parse the version number from it's output:
```
$ gtbin chatter=1 mode=h
This is gtbin version ScienceTools-v9r33p0-fssc-20140520
Caught N3tip12TipExceptionE at the top level: Unable to open file named "/home/mmohamed/fermi_enrico/output_data/MKN501_GCologn/MKN501_30days2014flare_56806-56836/MKN501_LAT_Analysis_Evt.fits" with read only access (CFITSIO ERROR 104: could not open the named file)
```
I'm not sure this is a good method though ... many ScienceTools don't print a version number (e.g. `gtlike` and `gtselect`) and some report different version numbers:
```
$ gtsrcid chatter=1 mode=h
This is gtsrcid version v2r3p4
ERROR catalogAccess (IN getMaxNumRows) : FILENAME "../../data/3EG.fits" cannot be opened
```
I think if `gtbin` doesn't get updated in a given release it will report an older version of the ScienceTools than the one the user really has.

@davidsanchez Feel free to do this however you like and let me know if you want me to implement a function to get the version number from the `gtbin` output via [subprocess](https://docs.python.org/2/library/subprocess.html)

**Comment by davidsanchez** [comment]
Hi,

thanks for the input. I have not strong feeling but I will go for using gtbin output
D

**Comment by davidsanchez** [comment]
I have close this issue. reopen it if needed
