### ISSUE TITLE
enrico_sed error

### ISSUE THREAD

**Issue by astrolog1986** [gammapy/enrico#75]
Hi everyone,

If enrico_sed results this message (it works but with this message) :
<<Minos error encountered for parameter 59.
Attempting to reset free parameters.
beta :  0.06 +/-  0.00  1e+00
Eb :  914.50   1e+00
The covariance matrix is :
[[  6.92082887e-04   1.21018965e-05   5.10972909e-05]
 [  1.21018965e-05   1.31702388e-04  -2.75753739e-05]
 [  5.10972909e-05  -2.75753739e-05   2.36359338e-05]]
......
.......>>
How we can check which is the "parameter 59" ?
If we obtain this message does it mean that the fit did not converge ? 

Thank you in advance !

**Comment by davidsanchez** [comment]
Hi, 
this is only the message which I don't understand. This is also output of MINUIT and then part of the gtlike tool
cheers
david

**Comment by astrolog1986** [comment]
Hi David,

Thank you for your answer! I am sorry I copied small part of the output. This is full output from enrico (after FitMaker). I would like to ask about the message "Minos error encountered for parameter 59"
How we can check which is the "parameter 59" ?
If there is this kind of message in the output does it mean that the fit did not converge ?

Thank you in advance!
The output
<<[FitMaker]: Results for the Fit
Source Name    Npred    TS
Values and (MINOS) errors for source1
TS :  30136.429653
Info in <Minuit2>: VariableMetricBuilder: no improvement in line search
Info in <Minuit2>: VariableMetricBuilder: machine accuracy limits further improvement.
Info in <Minuit2>: VariableMetricBuilder: INVALID function minimum - edm is above tolerance, : edm = 0.000126688
Info in <Minuit2>: VariableMetricBuilder: Required tolerance  is 10 x edmval  : edmval = 5e-06
Info in <Minuit2>: VariableMetricBuilder: no improvement in line search
Info in <Minuit2>: VariableMetricBuilder: machine accuracy limits further improvement.
Info in <Minuit2>: VariableMetricBuilder: INVALID function minimum - edm is above tolerance, : edm = 0.00014838
Info in <Minuit2>: VariableMetricBuilder: Required tolerance  is 10 x edmval  : edmval = 5e-06
Minos error encountered for parameter 57.
Attempting to reset free parameters.
norm :  1.91 +/-  0.03  1e-11
Info in <Minuit2>: VariableMetricBuilder: no improvement in line search
Info in <Minuit2>: VariableMetricBuilder: machine accuracy limits further improvement.
Info in <Minuit2>: VariableMetricBuilder: INVALID function minimum - edm is above tolerance, : edm = 0.000111949
Info in <Minuit2>: VariableMetricBuilder: Required tolerance  is 10 x edmval  : edmval = 5e-06
Info in <Minuit2>: VariableMetricBuilder: no improvement in line search
Info in <Minuit2>: VariableMetricBuilder: machine accuracy limits further improvement.
Info in <Minuit2>: VariableMetricBuilder: INVALID function minimum - edm is above tolerance, : edm = 0.000110145
Info in <Minuit2>: VariableMetricBuilder: Required tolerance  is 10 x edmval  : edmval = 5e-06
Minos error encountered for parameter 58.
Attempting to reset free parameters.
alpha :  1.84 +/-  0.01  1e+00
Info in <Minuit2>: VariableMetricBuilder: no improvement in line search
Info in <Minuit2>: VariableMetricBuilder: machine accuracy limits further improvement.
Info in <Minuit2>: VariableMetricBuilder: INVALID function minimum - edm is above tolerance, : edm = 0.000118691
Info in <Minuit2>: VariableMetricBuilder: Required tolerance  is 10 x edmval  : edmval = 5e-06
Info in <Minuit2>: VariableMetricBuilder: no improvement in line search
Info in <Minuit2>: VariableMetricBuilder: machine accuracy limits further improvement.
Info in <Minuit2>: VariableMetricBuilder: INVALID function minimum - edm is above tolerance, : edm = 0.000133429
Info in <Minuit2>: VariableMetricBuilder: Required tolerance  is 10 x edmval  : edmval = 5e-06
Minos error encountered for parameter 59.
Attempting to reset free parameters.
beta :  0.06 +/-  0.00  1e+00
Eb :  914.50   1e+00
The covariance matrix is :
[[  6.92082887e-04   1.21018965e-05   5.10972909e-05]
 [  1.21018965e-05   1.31702388e-04  -2.75753739e-05]
 [  5.10972909e-05  -2.75753739e-05   2.36359338e-05]]


Source Flux  [1.00e+02 MeV, 3.00e+05 MeV] : 
3FGL J0136.5+3905   Integral Flux : 2.50e-08 +/-  0.00e+00 ph/cm2/s
3FGL J0137.0+4752   Integral Flux : 8.05e-08 +/-  0.00e+00 ph/cm2/s
3FGL J0149.6+4846   Integral Flux : 8.06e-10 +/-  4.87e-10 ph/cm2/s
3FGL J0152.2+3707   Integral Flux : 8.38e-09 +/-  1.43e-09 ph/cm2/s
3FGL J0154.1+4642   Integral Flux : 1.47e-10 +/-  3.18e-10 ph/cm2/s
3FGL J0154.9+4433   Integral Flux : 5.78e-09 +/-  9.77e-10 ph/cm2/s
3FGL J0156.3+3913   Integral Flux : 1.41e-08 +/-  1.38e-09 ph/cm2/s
3FGL J0202.5+4206   Integral Flux : 4.23e-09 +/-  1.06e-09 ph/cm2/s
3FGL J0208.6+3522   Integral Flux : 1.22e-09 +/-  0.00e+00 ph/cm2/s
3FGL J0209.5+4449   Integral Flux : 1.93e-09 +/-  6.23e-10 ph/cm2/s
3FGL J0218.1+4233   Integral Flux : 7.41e-08 +/-  2.47e-09 ph/cm2/s
3FGL J0218.9+3642   Integral Flux : 5.81e-08 +/-  2.17e-09 ph/cm2/s
3FGL J0221.1+3556   Integral Flux : 8.91e-08 +/-  0.00e+00 ph/cm2/s
3FGL J0223.6+3927   Integral Flux : 1.04e-08 +/-  1.43e-09 ph/cm2/s
3FGL J0230.8+4032   Integral Flux : 3.29e-08 +/-  1.68e-09 ph/cm2/s
3FGL J0248.5+4232   Integral Flux : 4.92e-09 +/-  1.15e-09 ph/cm2/s
3FGL J0252.3+3830   Integral Flux : 1.85e-08 +/-  1.68e-09 ph/cm2/s
3FGL J0303.6+4716   Integral Flux : 2.74e-08 +/-  1.97e-09 ph/cm2/s
source1   Integral Flux : 1.17e-07 +/-  2.51e-09 ph/cm2/s
gll_iem_v06   Integral Flux : 5.67e-04 +/-  2.81e-06 ph/cm2/s
iso_P8R2_SOURCE_V6_v06   Integral Flux : 9.95e-05 +/-  1.96e-06 ph/cm2/s


# ************************************************************
# ***   5    PlotSED --- Generate SED plot
# ************************************************************

[Result]: Decorrelation energy : 1.00e+03 MeV
[Result]: Diffential flux  at the Decorrelation energy : 1.62e-11 +/-  2.23e-13 ph/cm2/s/MeV
[Result]: SED value at the Decorrelation energy : 2.59e-11 +/-  3.57e-13 erg/cm2/s

/opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/bin/python: error while loading shared libraries: /opt/Fermi/x86_64-unknown-linux-gnu-libc2.5/bin/python: wrong ELF class: ELFCLASS64
Info in <TCanvas::Print>: eps file 
/Spectrum/SED_source1_LogParabola_CountsPlot.eps has been created
Info in <TCanvas::SaveSource>: C++ Macro file: 
/Spectrum/SED_source1_LogParabola_CountsPlot.C has been generated
Info in <TCanvas::Print>: eps file 
/Spectrum/SED_source1_LogParabola_ResPlot.eps has been created
Info in <TCanvas::SaveSource>: C++ Macro file: 
/Spectrum/SED_source1_LogParabola_ResPlot.C has been generated
 >>

**Comment by davidsanchez** [comment]
This are message from MINUIT and enrico do not manage the fit and MINUIT.
Here, the only problem you have is that MINOS cannot compute errors. The fit should be ok but you can  
check by using enrico_scan  (minos is run on the source parameters only, then paramters 57, 58 and 59 are the source paramters)

best
david

**Comment by davidsanchez** [comment]
I have close this issue. reopen it if needed
