### ISSUE TITLE
gtsrcmaps error for enrico_sed & enrico_lc commands

### ISSUE THREAD

**Issue by pkar29** [gammapy/enrico#77]
Hi,

I keep running into this error for both enrico_sed and enrico_lc commands. Also I cannot quite get python to run, but i am think thats not the problem here. I am not quite sure whats happening and would really appreciate some help. Here is the error:
```
# ************************************************************
# ***   7   gtsrcmap --- Make a source map
# ************************************************************
time -p /home/payel/Softwares/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17/x86_64-un
known-linux-gnu-libc2.17/bin/gtsrcmaps scfile=../L1508101743513DF50DE793_SC00.fits sctable="SC_DATA" expcube
=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_
LC_0_ltCube.fits cmap=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240
.5+6113_LAT_Analysis_LC_0_CCUBE.fits srcmdl=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/3FGL J
0240.5+6113_LogParabola_model.xml bexpmap=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCur
ve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_BinnedMap.fits outfile=/home/payel/Fermi_Analysis/lsi61303_200
8_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_srcMap.fits irfs="CALDB" evtype="IN
DEF" convol=yes resample=yes rfactor=2 minbinsz=0.1 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=2 c
lobber=yes debug=no gui=no mode="ql"
Parameter "expcube" duplicated on command line.
Parameter "expcube" duplicated on command line.
Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtsrcmaps; Ape exception code
 19 (at hoops_ape.cxx: 435)
Traceback (most recent call last):
  File "/home/payel/Softwares/enrico//bin/enrico_lc", line 29, in <module>
    lc.MakeLC()
  File "/home/payel/Softwares/enrico/enrico/lightcurve.py", line 174, in MakeLC
    self._MakeLC()
  File "/home/payel/Softwares/enrico/enrico/lightcurve.py", line 134, in _MakeLC
    run(self.configfile[i])#run in command line
  File "/home/payel/Softwares/enrico/enrico/RunGTlike.py", line 55, in run
    FitRunner,Fit = GenAnalysisObjects(config)
  File "/home/payel/Softwares/enrico/enrico/RunGTlike.py", line 43, in GenAnalysisObjects
    FitRunner = Analysis(folder, config, tag="", verbose = verbose)
  File "/home/payel/Softwares/enrico/enrico/RunGTlike.py", line 18, in Analysis
    FitRunner.GenerateFits() #Generates fits files
  File "/home/payel/Softwares/enrico/enrico/fitmaker.py", line 67, in GenerateFits
    self.obs.SrcMap()
  File "/home/payel/Softwares/enrico/enrico/gtfunction.py", line 317, in SrcMap
    srcMaps.run()
  File "/home/payel/Softwares/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17/x86_64-un
known-linux-gnu-libc2.17/lib/python/GtApp.py", line 72, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtsrcmaps execution failed
```

Thank You,

**Comment by cdeil** [comment]
What if you directly execute the command?
```
time -p /home/payel/Softwares/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17/x86_64-un
known-linux-gnu-libc2.17/bin/gtsrcmaps scfile=../L1508101743513DF50DE793_SC00.fits sctable="SC_DATA" expcube
=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_
LC_0_ltCube.fits cmap=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240
.5+6113_LAT_Analysis_LC_0_CCUBE.fits srcmdl=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/3FGL J
0240.5+6113_LogParabola_model.xml bexpmap=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCur
ve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_BinnedMap.fits outfile=/home/payel/Fermi_Analysis/lsi61303_200
8_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_srcMap.fits irfs="CALDB" evtype="IN
DEF" convol=yes resample=yes rfactor=2 minbinsz=0.1 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=2 c
lobber=yes debug=no gui=no mode="ql"
```

Do you then also get the same error?
```
Parameter "expcube" duplicated on command line.
```

(I haven't used Enrico in ages and won't be very helpful ... @davidsanchez can probably help.)

**Comment by pkar29** [comment]
Hi @cdeil,

If I try and run gtsrcmaps on command line it works fine. But trying the execute the above command exactly gives the same error:

[payel@karpc myanalysis]$ time -p /home/payel/Softwares/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/bin/gtsrcmaps scfile=../L1508101743513DF50DE793_SC00.fits sctable="SC_DATA" expcube=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_ltCube.fits cmap=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_CCUBE.fits srcmdl=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/3FGL J0240.5+6113_LogParabola_model.xml bexpmap=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_BinnedMap.fits outfile=/home/payel/Fermi_Analysis/lsi61303_2008_20015/myanalysis/LightCurve_20bins//3FGLJ0240.5+6113_LAT_Analysis_LC_0_srcMap.fits irfs="CALDB" evtype="INDEF" convol=yes resample=yes rfactor=2 minbinsz=0.1 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Parameter "expcube" duplicated on command line.
Parameter "expcube" duplicated on command line.
Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtsrcmaps; Ape exception code 19 (at hoops_ape.cxx: 435)
real 0.34
user 0.31
sys 0.02

**Comment by davidsanchez** [comment]
Hi

my guess is that the path name are not well recognize. maybe a '+' or a space
cheers
david

**Comment by pkar29** [comment]
In the config file the name of the source appears as 

target]
        name = 3FGLJ0240.5+6113

Do you think that is the problem? What should be done in that case?
When I try to create an xml file, the name always appears like this 3FGL J0240.5+6113_LogParabola_model.xml
Should I manually change the name after the xml file is created, would it still be identified in that case?
What is it that I should do exactly?

Payel

**Comment by davidsanchez** [comment]
I was thinking to  the directory path. try to remove the space and +

**Comment by pkar29** [comment]
sorry for being slow to understand, I cannot find the directory name where there is a space or a +
Can you please copy paste that part from the error?
Thank You

**Comment by davidsanchez** [comment]
This is in the source name, you have to change it
cheers

**Comment by pkar29** [comment]
Thank You! This solves it. I thought it has to be of the same format as the xml file.

**Comment by KaurNav** [comment]
Hi,

I am getting an error while running enrico_sed. I have tried all the solutions mentioned above and from here-there, but nothing seem to work. For a check, I performed step-by-step analysis as given in enrico documentation and it works perfectly fine.  
Below is an error that I am encountering. Please help me to resolve this issue.


----------------
[sameer@prlhpcms01 myanalysis]$ time -p /home/sameer/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/bin/gtsrcmaps scfile=/shared_phpc_home/home/sameer/Navpreet/***/myanalysis/L170303013212BD7490F170_SC00.fits sctable="SC_DATA" expcube=/shared_phpc_home/home/sameer/Navpree/t***/myanalysis/**_LAT_1d_ltCube.fits cmap=/shared_phpc_home/home/sameer/Navpreet/***/myanalysis/**_LAT_1d_CCUBE.fits srcmdl=/shared_phpc_home/home/sameer/Navpreet/***/myanalysis/**_PowerLaw2_model.xml bexpmap=/shared_phpc_home/home/sameer/Navpreet/***/myanalysis/**_LAT_1d_BinnedMap.fits outfile=/shared_phpc_home/home/sameer/Navpreet/***/myanalysis/**_1d_srcMap.fits irfs="CALDB" evtype="INDEF" convol=yes resample=yes rfactor=2 minbinsz=0.1 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=2 clobber=yes debug=no gui=no mode="ql"
Parameter::extractDomData:
In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.
Caught St12out_of_range at the top level: Parameter::extractDomData:
In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.
real 20.77
user 15.05
sys 2.95

-----

Hopefully,
Nav
