### ISSUE TITLE
enrico_xml failing to add sources

### ISSUE THREAD

**Issue by ralphbird** [gammapy/enrico#79]
When runnign enrico_xml multiple sources, though found in the catalogue, are not added to the xml file, this is due to the test e.g. 
 ```python
if spectype == 'PowerLaw': 
```
not passing due to whitespace, this is corrected by using 
```python
 if spectype.strip() == 'PowerLaw': 
```
or by changing         
```python
spectype = srclist[i].get('SpectrumType') 
```
to         
```python
spectype = srclist[i].get('SpectrumType').strip()
```

**Comment by davidsanchez** [comment]
thanks a lot for the fix
david
