### ISSUE TITLE
enrico_plot_lc error, enrico_lc seems to work fine.

### ISSUE THREAD

**Issue by pkar29** [gammapy/enrico#80]
Hi,
After I have made a global fit with enrico_sed, I wanted to make a light curve on the day to day bin. Before this I tried running with the default 20 bins. Although the enrico_lc did not give any errors to me while trying to plot with enrico_plot_lc I get the following:

Bin  18  Start= 348649922.0  Stop= 349176962.0
Bin  19  Start= 349176962.0  Stop= 349704002.0

[LightCurve]: Reading files produced by enrico
[LightCurve] Warning: problem in errors calculation for : /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/Config_1_339690242.0_340217282.0
Job Number :  1
[LightCurve] Warning: Please have a look at this job log file
Flux +/- error =  4.13892027381e-07  +/-  1.14557881177e-08
V(Npred) =  16.0798829182

[LightCurve] Warning: problem in errors calculation for : /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/Config_14_346541762.0_347068802.0
Job Number :  14
[LightCurve] Warning: Please have a look at this job log file
Flux +/- error =  1.87890304021e-07  +/-  1.43439896437e-08
V(Npred) =  11.1087906966

TROOT::Append:0: RuntimeWarning: Replacing existing TH1: ghnpred (Potential memory leak).
Info in <TCanvas::Print>: png file /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/3FGLJ0240.5+6113_Npred.png has been created
Info in <TCanvas::Print>: eps file /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/3FGLJ0240.5+6113_Npred.eps has been created
Info in <TCanvas::SaveSource>: C++ Macro file: /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/3FGLJ0240.5+6113_Npred.C has been generated
Info in <TCanvas::Print>: png file /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/3FGLJ0240.5+6113_TS.png has been created
Info in <TCanvas::Print>: eps file /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/3FGLJ0240.5+6113_TS.eps has been created
Info in <TCanvas::SaveSource>: C++ Macro file: /home/payel/Fermi_Analysis/lsi_1112/power/LightCurve_20bins/3FGLJ0240.5+6113_TS.C has been generated
Traceback (most recent call last):
  File "/home/payel/Softwares/enrico/bin/enrico_plot_lc", line 30, in <module>
    lc.PlotLC()
  File "/home/payel/Softwares/enrico/enrico/lightcurve.py", line 188, in PlotLC
    self._PlotLC()
  File "/home/payel/Softwares/enrico/enrico/lightcurve.py", line 323, in _PlotLC
    gTHIndex,TgrIndex,ArrowIndex = plotting.PlotLC(Time,TimeErr,Index,IndexErr)
  File "/home/payel/Softwares/enrico/enrico/plotting.py", line 257, in PlotLC
    ArrowSize = (max(x) + max(xErr) * 1.3 -
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Also the diagnostic plots are being created without any problem. Please help.

**Comment by davidsanchez** [comment]
Hi,
Did you fix the index in the xml file?
best
david

**Comment by davidsanchez** [comment]
I have close this issue. reopen it if needed
