### ISSUE TITLE
gtexpcube2 outdated options for PASS8

### ISSUE THREAD

**Issue by robertazanin** [gammapy/enrico#81]
At http://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html
it is written:

"If you provide gtexpcube2 a filename for your counts cube, it will use the information from that file to define the geometry of the exposure map. This is legacy behavior and will not give you the necessary 20Â° buffer you need to completely account for the exposure of nearby sources. (It will also cause an error in the next step.) Instead, you should specify the appropriate geometry for the exposure map, remembering that the counts cube used 0.2 degree pixel binning. To do that, enter 'none' when asked for a Counts cube."

What ENRICO does is  to pass gtexpcube2 the CCUBE from which it takes the geometry (hence putting the xref and yref nxpix and nypix options as INDEF). Would it be possible to set these geometrical options taking the numbers from the configuration files as now suggested in the Fermi SCience Tool tutorial?

Thank you in advance, 
Roberta  

cc @zblz @davidsanchez

**Comment by davidsanchez** [comment]
Hi

the function GtBinnedMap in gtfunction.py set up the use of gtexpcube2 by giving a ccube file. this cube file is generated with 

        evtbin['nxpix'] = self.npix
        evtbin['nypix'] = self.npix
        evtbin['binsz'] = self.binsz

and 
        #Maps binning
        self.binsz     = self.Configuration['space']['binsz']
        self.npix      = int(2*self.roi/sqrt(2.)/self.binsz)

best
david

**Comment by davidsanchez** [comment]
I have close this issue. reopen it if needed
