### ISSUE TITLE
Power Law Model Definition with Crab Pulsar Error

### ISSUE THREAD

**Issue by JamieAGraham** [gammapy/enrico#84]
In the 3FGL the Crab has 3 components, a PLExpCutoff for the pulsar, soft power-law for synchrotron and a hard power law for the IC emission (arxiv:1501.02003). The synchrotron component is a power law "3FGL J0534.5+2201s" with a 3FGL index of 5.71589. In the function addPSPowerLaw1 in xml_model.py, the index bounds are set automatically to [0,5].

Due to this, enrico_sed will fail when it reaches gtsrcmaps if you have the Crab in your ROI. Is it worth adding a special case for the Crab? I quickly ran through the 3FGL and this is the only source with |gamma| > 5.

**Comment by davidsanchez** [comment]
Dear Jamie,

the best is to change the xml model for this source after the production by enrico_xml.

best
david

**Comment by JamieAGraham** [comment]
Hi David,

Yes, that was what I ended up doing, I just thought that since make3FGLxml.py automatically sets the upper index limit to 10 (or lower limit, depending on whether your scale for the index is +1.0 or -1.0), it might be worth following suit in enrico, since it would avoid this issue as well.

Best wishes,
Jamie

**Comment by davidsanchez** [comment]
why not. I put this on my long todo list then

**Comment by davidsanchez** [comment]
done
