### ISSUE TITLE
RuntimeError: gtselect execution failed

### ISSUE THREAD

**Issue by blazar716** [gammapy/enrico#86]
Hello everyone,

I got the following error message. Any help please?

mypc@user:~/home/enrico$ enrico_sed Myconfig.conf
Plotter is MatPlotlib
# ************************************************************
# *** SUMMARY:  ***
# ************************************************************
Source	=	3C 279
RA	=	193.98  degrees
Dec	=	-5.82  degrees
Start	=	239557417.0   MET (s)
Stop	=	255398400.0   MET (s)
ROI	=	15.0  degrees
E min	=	100.0  MeV
E max	=	300000.0  MeV
IRFs	=	CALDB
evclass	=	128
evtype	=	3
Corresponding IRFs	=	('P8R2_SOURCE_V6', ['BACK', 'FRONT'])

# ************************************************************
# ***   1   gtselect --- Select data from library
# ************************************************************
time -p /home/mypc/ICTS/ScienceTools-v10r0p5-fssc-20150518A-source/x86_64-unknown-linux-gnu-libc2.13-38+/bin/gtselect infile=/home/mypc/ICTS/enrico/Data/download/events.lis outfile=/home/mypc/ICTS/enrico/3C 279_LAT_Analysis_Evt.fits ra=193.98 dec=-5.82 rad=15.0 tmin=239557417.0 tmax=255398400.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evclsmin=0 evclsmax=10 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
Parameter "infile" duplicated on command line.
Parameter "infile" duplicated on command line.
Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtselect; Ape exception code 19 (at hoops_ape.cxx: 435)
Traceback (most recent call last):
  File "/home/mypc/ICTS/enrico/bin/enrico_sed", line 58, in <module>
    sed(config,infile)
  File "/home/mypc/ICTS/enrico/bin/enrico_sed", line 13, in sed
    run(infile)
  File "/home/mypc/ICTS/enrico/enrico/RunGTlike.py", line 57, in run
    FitRunner,Fit = GenAnalysisObjects(config)
  File "/home/mypc/ICTS/enrico/enrico/RunGTlike.py", line 41, in GenAnalysisObjects
    FitRunner = Analysis(folder, config, tag="", verbose = verbose)
  File "/home/mypc/ICTS/enrico/enrico/RunGTlike.py", line 16, in Analysis
    FitRunner.GenerateFits() #Generates fits files
  File "/home/mypc/ICTS/enrico/enrico/fitmaker.py", line 49, in GenerateFits
    self.obs.FirstCut()
  File "/home/mypc/ICTS/enrico/enrico/gtfunction.py", line 196, in FirstCut
    filter.run()
  File "/home/mypc/ICTS/ScienceTools-v10r0p5-fssc-20150518A-source/x86_64-unknown-linux-gnu-libc2.13-38+/lib/python/GtApp.py", line 72, in run
    raise RuntimeError, self.appName + " execution failed"
RuntimeError: gtselect execution failed

**Comment by davidsanchez** [comment]
Hello,

Did you try to run the gtselect command by copy and past this

time -p /home/mypc/ICTS/ScienceTools-v10r0p5-fssc-20150518A-source/x86_64-unknown-linux-gnu-libc2.13-38+/bin/gtselect infile=/home/mypc/ICTS/enrico/Data/download/events.lis outfile=/home/mypc/ICTS/enrico/3C 279_LAT_Analysis_Evt.fits ra=193.98 dec=-5.82 rad=15.0 tmin=239557417.0 tmax=255398400.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evclsmin=0 evclsmax=10 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" 


My guess is that the + in the path is not well recognised

cheers
david

**Comment by blazar716** [comment]
Thank you Daid. It was the space in "3C 279" that was making mess. Now it perfectly works.

**Comment by blazar716** [comment]
Thank you David. It was the space in "3C 279" that was making mess. Now it perfectly works.
