### ISSUE TITLE
UnboundLocalError: local variable 'IndexName' referenced before assignment

### ISSUE THREAD

**Issue by blazar716** [gammapy/enrico#87]
Hi David,

After executing all the previous steps successfully, it's giving the following error while trying to plot the LC.

user@user-Inspiron-5721:~/fermitool/Enrico$ enrico_plot_lc myanalysis.conf
[LightCurve]: Running LC with 20 bins
Bin  0  Start= 455932803.0  Stop= 455945763.0
Bin  1  Start= 455945763.0  Stop= 455958723.0
Bin  2  Start= 455958723.0  Stop= 455971683.0
Bin  3  Start= 455971683.0  Stop= 455984643.0
Bin  4  Start= 455984643.0  Stop= 455997603.0
Bin  5  Start= 455997603.0  Stop= 456010563.0
Bin  6  Start= 456010563.0  Stop= 456023523.0
Bin  7  Start= 456023523.0  Stop= 456036483.0
Bin  8  Start= 456036483.0  Stop= 456049443.0
Bin  9  Start= 456049443.0  Stop= 456062403.0
Bin  10  Start= 456062403.0  Stop= 456075363.0
Bin  11  Start= 456075363.0  Stop= 456088323.0
Bin  12  Start= 456088323.0  Stop= 456101283.0
Bin  13  Start= 456101283.0  Stop= 456114243.0
Bin  14  Start= 456114243.0  Stop= 456127203.0
Bin  15  Start= 456127203.0  Stop= 456140163.0
Bin  16  Start= 456140163.0  Stop= 456153123.0
Bin  17  Start= 456153123.0  Stop= 456166083.0
Bin  18  Start= 456166083.0  Stop= 456179043.0
Bin  19  Start= 456179043.0  Stop= 456192003.0

[LightCurve]: Reading files produced by enrico
Traceback (most recent call last):
  File "/home/user/fermitool/Enrico/bin/enrico_plot_lc", line 30, in <module>
    lc.PlotLC()
  File "/home/user/fermitool/Enrico/enrico/lightcurve.py", line 197, in PlotLC
    self._PlotLC()
  File "/home/user/fermitool/Enrico/enrico/lightcurve.py", line 238, in _PlotLC
    IndexErrName = 'd' + IndexName
UnboundLocalError: local variable 'IndexName' referenced before assignment

**Comment by davidsanchez** [comment]
Hi

Is the index of the source free?

david

**Comment by blazar716** [comment]
Thank you, David.

I figured out.
