### ISSUE TITLE
enrico_download to be able to support reprocessed data with diffuse response

### ISSUE THREAD

**Issue by mireianievas** [gammapy/enrico#95]
Is there any plan to implement the download and use of reprocessed data with diffuse response columns in enrico_download?. It might be handy for some unbinned analyses.

http://fermi.gsfc.nasa.gov/ssc/data/access/
ftp://heasarc.gsfc.nasa.gov/FTP/fermi/data/lat/weekly/diffuse/

**Comment by davidsanchez** [comment]
Hi

this is what is already downloaded

cheers
david
